--liquibase formatted sql

CREATE TABLE IF NOT EXISTS user_ads
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,

    user_name TEXT            NOT NULL,

    password TEXT             NOT NULL,

    first_name TEXT           NOT NULL,

    last_name TEXT            NOT NULL,

    phone TEXT                ,

    email TEXT                NOT NULL,

    image INTEGER NOT NULL REFERENCES image(id),

    role TEXT                  NOT NULL

);

CREATE TABLE IF NOT EXISTS ads
(
    pk INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,

    author INTEGER NOT NULL REFERENCES user_ads(id),

    price INTEGER NOT NULL ,

    title TEXT NOT NULL ,

    description TEXT ,

    image INTEGER NOT NULL REFERENCES image(id)
);

CREATE TABLE comment
(
    ad_id INTEGER NOT NULL REFERENCES ads(pk),

    author INTEGER NOT NULL REFERENCES user_ads(id),

    comment_id INTEGER GENERATED BY DEFAULT AS IDENTITY ,

    created_at BIGINT NOT NULL ,

    text TEXT,

    PRIMARY KEY (ad_id,comment_id)

);


CREATE TABLE IF NOT EXISTS image
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path TEXT,
    file_size BIGINT,
    media_type TEXT
);






