--liquibase formatted sql

create table ads
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    price       integer not null,
    title       varchar(255),
    author_id   bigint,
    image_id    bigint
);


create table ads_comment
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp,
    text       varchar(255),
    pk_ads     bigint,
    author_id  bigint
);

create table image
(
    id         bigint generated by default as identity
        primary key,
    data       bytea,
    file_size  bigint not null,
    media_type varchar(255)
);



create table users
(
    id         bigint generated by default as identity
        primary key,
    city       varchar(255),
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    phone      varchar(255),
    reg_date   timestamp,
    role       varchar(255),
    image_id   bigint
);





